engines:
  rubocop:
    enabled: false
  golint:
    enabled: false
  eslint:
    enabled: true
    channel: "eslint-2"
    checks:
      comma-dangle:
        enabled: false
  csslint:
    enabled: false
  duplication:
    enabled: false
  fixme:
    enabled: false
ratings:
  paths:
  - "gulp/**.js"
  - "gulpfile.js"
  - "src/js/**.js"
  - "test/**.js"
exclude_paths:
  - "dist/**"
  - "src/js/polyfills/**"
  - "test/coverage/**"
  - "test/jasmine/**"
  - "test/karma/**"
