engines:
  rubocop:
    enabled: false
  golint:
    enabled: false
  eslint:
    enabled: true
    channel: "eslint-3"
    checks:
      comma-dangle:
        enabled: true
  csslint:
    enabled: false
  duplication:
    enabled: false
  fixme:
    enabled: false
ratings:
  paths:
  - "gulp/tasks/**.js"
  - "gulpfile.js"
  - "test/**.js"
  - "src/js/**"
  - "src/docs/js/**.js"
exclude_paths:
  - "dist/**/*"
  - "docs/**/*"
  - "src/docs/js/ie10-viewport-bug-workaround.js"
  - "src/js/private/polyfills/**"
  - "test/coverage/**"
  - "test/jasmine/**"
  - "test/karma/**"
