engines:
  rubocop:
    enabled: false
  golint:
    enabled: false
  eslint:
    enabled: true
    checks:
      comma-dangle:
        enabled: false
  csslint:
    enabled: false
  duplication:
    enabled: false
  fixme:
    enabled: false
ratings:
  paths:
  - "src/js/**.js"
  - "test/**.js"
  - "dist/acte.js"
  - "gulpfile.js"
  - "gulp/**.js"
exclude_paths:
  - "src/css/**"
  - "test/coverage/**"
  - "test/jasmine/lib/**"
