language: node_js
node_js:
- '4'
- '5'
- '6'
matrix:
  include:
    - node_js: 'stable'
      env:
        - SAUCELABS='1'
        - COVERALLS='1'
      addons:
        sauce_connect: true
          username: "DtZozuBuNizjSXVUAUWY1f53pHyGt/feaehK6toYu4Bl5OQh+b6nOXq2xlDsiHcjwYEu105LsN8JxjQKa0LSC/fIJzhsJ1y0YBj35/r9TjH5CUtlA49Fdn9Yxnh2PmFkbciLytEac0PgRdQZ7g+aQ3gJI4BIJaWnNEFUAoH2dZof0dltwEkD7G9BUL1nPAbl1rd5nfTDtX9Nry29XPxU6WJKG1lLlezYrzbGKes0W6WCB1KNJRGDddTH1ChrT7mdyq1zcvopvO3/jGI4mHvVFP1o14U+Gfvo/Suv19ik7BwOkggMDDkh6nSstYNDf1t/gJiq3K+ukeJ5BLjP1ITofMM0jHtVwijalY2qfI4NGHxqb+1MnjlsqCKpL+7vHKj2gsZYNsawcHbqrkXhK7ZNanS/Kh5xy08eQFMjjHg/SwO52VTVJs9MGo4FYx2hm2XjC2C/dFU4ivERsIyQUKr+37v0lQO3v2bHrUeOVRGsbULyH6DNXXZvvels5dp9bOhXvZCrrh+bupuJ5XEL8hNdkiyH9rk1xHkWytNnnr8owmT4edtZrOFEgZouVwUwThxqAHlwmYcAI+o5HB930oP+8vZki223ehlKmDykazLRkop2u444cXbLDKBlyZLxTGpGxgje2rkSRhz8ROeq/Cw1ynvnrwucepw+MXucn5jJkuI="
          access_key: "kPyOAfEICLfpbQzprUesMmhOMq1d5KjRmzkSgcqMD6YJCelQ+bgxUGaNt6ACXzanruKjFCnLUf5GOlt/xpSiMhC5gTiqPpjecwSkvy4l5ocMcw42ZZ2XXEBNIp52VSLW5uKxzWd0dwZmsjj3M9rQh9MAmtjaje4mqPHE9F6ud4BjzoDzKE/qIz0/oL+ty99T/SCZTKglrhudkmuBoMF8g0v7ROHsdHfq7SYyFv9A6GhweHy/YxJ891sB/NOXofqGQ0hXYmr0qv2ucmSLnPox93yxrT0gpP4rwu73oywGhnjCBkSfV6EPUMtk4frN4dglPcCR00C6RC34TRugaPbBh0VjTKSHCfXmzUSZWvomL8hUm+AKBW3ErqacaHJJ4pv3XGcSwv0GwYa2cWcpC1P7k7D7XG7jfNSoG1BUNnFoUhGxQOoPPCF+ao95gfUzhzYGHUTwVYnkPMpUX+3uKNb26sdFQET4T+ZTxk26B0bfz1uMu1/VNq82nTakTXWHA43rDamifnkgkt0j5qghlA9ZHBig/5BkMlsw7FgvvZmzkN24jn4HYVZosEwEPTEXANT2CWx4sY6EX7VgVXZkYrN0eHWztQ5RyUBR3x3Zef+nmuEls+Z76Tn/oIoUf/XpSYICZxWucZJJLw4p5E0M09ftBSb1Pau02L+9lNFzXAAbAJ4="
branches:
  only:
  - master
before_install:
 - "export TRAVIS_COMMIT_MSG=\"$(git log --format=%B --no-merges -n 1)\""
 - if echo "$TRAVIS_COMMIT_MSG" | grep '\[-saucelabs\]'; then unset SAUCELABS; fi
 - echo "SAUCELABS = "${SAUCELABS}
 - if echo "$TRAVIS_COMMIT_MSG" | grep '\[-coveralls\]'; then unset COVERALLS; fi
 - echo "COVERALLS = "${COVERALLS}
before_script:
  - npm install -g gulp
  - npm install -g bower
  - npm install -g karma-cli
  - npm install
  - bower install
script:
  - gulp default
after_script:
  - ./node_modules/.bin/gulp tests.coverage
  - ./node_modules/.bin/gulp tests.coveralls
  - ./node_modules/.bin/gulp tests.saucelabs
env:
  global:
  - TRAVIS_SECURE_ENV_VARS='true'
  - secure: foS0Pkw3CQVRJJla5ImP2N8KdjpM18SR0/xMphX0pD0T9erhDRfAiwwHNDK5tsmvG0/mClwWSl0IMgxAAmBJFCBKwhYm85G0w86k7WVXSYDYb7cQKXCwGek7T5PExEgo+clvv7hZVItAyMJJ0J4KQ0L2HVMxHySwsqrOQd0mfW1G2XOFCKlA7raV03xarbQKxa/KEXO2lZ8Q+yOiG+SbzLCHUXgfysH6oTnzjJktHgUQcMoqSqXDKkfKCtfiNU/8a9ouvgEpKOGEdFG/q1Yg/I0FEm9Yucbfh2T4Gze8Rk0ypBMeZeKDc9LXoeIz5AZDhtNtBxQxs4AedPTe2FgCVLGcKbRCI56u8FtmJM5nJtTi+iNbXopwa45uQUXpGmRDZv9Fue+Gnlqua3RTA8Q0ZQOwlI0IDMcrETiOT9o4ZMiqyIKzHm51Q/p3dVYvB3edEhaz3gtIi8nI9ZJY1W/J9XvChdM7uH/ZonWP5iSQ6jzQX1feSigJR22Z2F1ROWeo2AGEOO4KQ3J/uglBt4ydJEcN5Gvk65IAyVGdxfmuL8mYcTYznxmMzFl7G1Cd5VvKwAeXk4OOj8sGfw+HcWieCEu6HJTbWpTPiJa6SaDiC150bBp4SFtxRx6OZo+qCK5EjIrlmB4orOjH9Xs9hytIWf4Ik+ioqo5jdyAXg44YLW4=
  - secure: GHxnUOuoa7yF7t0xFwo+lWKcu7wpfoV1XIbX4U0PeiR0m0/GlnFYAcy12KWYNF+no8MNdu0pcuQ49xwFHt5qYKZy51cn/ExC+zCVpoqRBo5mACRtl7QzPA6LqYZuzvMv6gsB0j4K3p5Vcnes9W3GIi7uc6pHxuaR7IozVbPFb6j+dhbtd2CBe25aSajcJ7ef/jeOSaJG+wtK3Xsb4eUpa2AveFvoq21C0r+oOaqdo2kfzQOhrnUlSJZJBuV35/KYVCCrsLj1QxZJd9QUO+swWxFY000/Aa2btSvuCla8jKXshl089CuWRVDCe3tHh8Im1zgfqZJRQSfhxtTQlcnKmnizfvFUH2XMPNZfdqZJ7I7br3Dmgu/COFwyMNGLxxY0eHJLl7rW6jI7e2VRMziXOGn5r7XF6hVFe/QCGLG/C9oKGgVqh65rgroBviwmdtlRQ1IlUAt51zMfdy/yLzT6LKHVBWCFt4cqefhZ0bGMVJQxZ2AEgqA3khVyUSGdJ6oZ/2d4BY/sVWJI0tdCMVRNzd7UGkH2Usdcm+1KBR3xA/TAtHG89DLDM2XmJ0TdpZGuvtB5DiNmqOceDWaBUr1+qeCtSR90Er/5tgPthjihFUGHnPB7UvA0Sk7casQTf7jza+zV38rt3SzqP8CYfUr71lwlDxzhHbMhOt+EaTJMCUk=
notifications:
  email:
    recipients:
    - gilles.toubiana@yahoo.fr
    on_failure: always
cache:
  directories:
    - node_modules
